### PR TITLE
Add support for hss-lms keys

### PR DESCRIPTION
**Pull request by bremoran**
This PR adds support for hss-lms keys through the use of pyhsslms.

### CODE REVIEW

**Comment by bremoran** [comment]
cc @russhousley

**Comment by russhousley** [comment]
Something is not quite right with the parse command...

(PY3) $suit-tool keygen -t hsslms -o hashsig1.prv
(PY3) $suit-tool pubkey -k hashsig1.prv -f hsslms -o hashsig1.pub
(PY3) $suit-tool sign -m manifest.suit -k hashsig1.prv -o foo.signed
(PY3) $suit-tool parse -m foo.signed

I get:

    raise SUITException(
suit_tool.manifest.SUITException: At <class 'suit_tool.manifest.SUITBWrapField.<locals>.SUITBWrapper'>: failed to load "860150fa6b4a53d5ad5fdfbe9de663e4d41ffe02501492af1425695e48bf429b2d51f2ab450f82840519840014a20b8202582000112233445566778899aabbccddeeff0123456789abcdeffedcba98765432100c1987d084051a0008440014a20b820258200123456789abcdeffedcba987654321000112233445566778899aabbccddeeff0c1a00012c22" as CBOR

**Comment by bremoran** [comment]
Thanks for testing. Unfortunately without either the input file, the CBOR, or the full text of the error dump, this will be hard to debug. I have run every example in the examples directory through the tool as you describe and none have returned an error.

**Comment by russhousley** [comment]
I sent the file manifest.suit file by email directly to you.

**Pull request merged**
